// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

// CreateOrderItem defines model for CreateOrderItem.
type CreateOrderItem struct {
	// Comment Comment to an order
	Comment *string `json:"comment,omitempty"`

	// ProductId Id of a product
	ProductId string `json:"productId"`

	// Quantity Quantity of a product
	Quantity int `json:"quantity"`

	// Timestamp Timestamp of an order in RFC3339 format
	Timestamp string `json:"timestamp"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Data CreateOrderItem `json:"data"`
}

// CreateOrderResponse defines model for CreateOrderResponse.
type CreateOrderResponse struct {
	Data CreatedOrder `json:"data"`
}

// CreatedOrder defines model for CreatedOrder.
type CreatedOrder struct {
	// Comment Comment to an order
	Comment *string `json:"comment,omitempty"`

	// Id Id of an order
	Id string `json:"id"`

	// ProductId Id of a product
	ProductId string `json:"productId"`

	// Quantity Quantity of a product
	Quantity int `json:"quantity"`

	// Timestamp Timestamp of an order in RFC3339 format
	Timestamp string `json:"timestamp"`
}

// Error defines model for Error.
type Error struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail string `json:"detail"`

	// Id Id of a request
	Id   string `json:"id"`
	Meta struct {
		// Timestamp Timestamp of the occurrence of the problem in RFC3339 format
		Timestamp string `json:"timestamp"`
	} `json:"meta"`

	// Status The HTTP status code applicable to this problem, expressed as a string value
	Status string `json:"status"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest
