// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

// CreateOrderItem defines model for CreateOrderItem.
type CreateOrderItem struct {
	// Comment Comment to an order
	Comment  *string       `json:"comment,omitempty"`
	Products []ProductItem `json:"products"`

	// Timestamp Timestamp of an order in RFC3339 format
	Timestamp string `json:"timestamp"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Data CreateOrderItem `json:"data"`
}

// CreateOrderResponse defines model for CreateOrderResponse.
type CreateOrderResponse struct {
	Data CreatedOrder `json:"data"`
}

// CreatedOrder defines model for CreatedOrder.
type CreatedOrder struct {
	// Comment Comment to an order
	Comment *string `json:"comment,omitempty"`

	// Id Id of created order
	Id       string        `json:"id"`
	Products []ProductItem `json:"products"`

	// Timestamp Timestamp of an order in RFC3339 format
	Timestamp string `json:"timestamp"`
}

// ErrorItem defines model for ErrorItem.
type ErrorItem struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail string `json:"detail"`

	// Id Identificator of a request
	Id     string       `json:"id"`
	Meta   ErrorMeta    `json:"meta"`
	Source *ErrorSource `json:"source,omitempty"`

	// Status The HTTP status code applicable to this problem, expressed as a string value
	Status string `json:"status"`
}

// ErrorMeta defines model for ErrorMeta.
type ErrorMeta struct {
	// Timestamp Timestamp of the occurrence of the problem in RFC3339 format
	Timestamp *string `json:"timestamp,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Errors []ErrorItem `json:"errors"`
}

// ErrorSource defines model for ErrorSource.
type ErrorSource struct {
	// Pointer a JSON Pointer [RFC6901] to the value in the request document that caused the error
	Pointer string `json:"pointer"`
}

// ProductItem defines model for ProductItem.
type ProductItem struct {
	// Id Id of a product
	Id string `json:"id"`

	// Quantity Quantity of a product
	Quantity int `json:"quantity"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest
